version: '3.4'
networks:
  mongonet:
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    networks:
      - mongonet
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: admin
    #   MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - './datadir:/data/db'
  # mongo-express:
  #   depends_on:
  #     - mongo
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - '8081:8081'
  #   # environment:
  #   #   ME_CONFIG_MONGODB_ADMINUSERNAME: admin
  #   #   ME_CONFIG_MONGODB_ADMINPASSWORD: admin
  #   networks:
  #     - mongonet
