version: '3.4'

services:
  db:
    image: mysql
    container_name: mysql-db # 容器名
    # command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci #设置utf8字符集
    command: --default-authentication-plugin=mysql_native_password
    # command: ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
    restart: always
    ports:
      - '13306:3306' #host物理直接映射端口为6606
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Shanghai
      # - MYSQL_USER: root
      # - MYSQL_PASS: root
    volumes:
      - 'D:/docker/shared/mysql/data:/var/lib/mysql'
      - 'D:/docker/shared/mysql/conf:/etc/mysql/conf.d'
      # - "D:/filestorage/avatar:/filestorage/avatar"
      # - "D:/aa:/video"
    build:
      context: .
      dockerfile: Dockerfile
