
version: '3.4'

services:
  # kong-database:
  #   image: cassandra:3
  #   container_name: kong-database
  #   ports:
  #     - 9042:9042
  #   # environment:
  #   #   - POSTGRES_USER=kong
  #   #   - POSTGRES_DB=kong
  #   #   - PGDATA=/tmp
  #   volumes:
  #     # - "./db:/var/lib/postgresql/data"
  #     - "./conssandradb:/var/lib/cassandra"
  #   networks: 
  #     - kong-network
  # kong-database:
  #   image: postgres:9.6
  #   container_name: kong-database
  #   ports:
  #     - 5432:5432
  #   environment:
  #     - POSTGRES_USER=kong
  #     - POSTGRES_DB=kong
  #     - PGDATA=/tmp
  #   volumes:
  #     # - "./db:/var/lib/postgresql/data"
  #     - "./db:/tmp"
  #   networks: 
  #     - kong-network
  # kong-migrations:
  #   image: kong
  #   environment:
  #     - KONG_DATABASE=postgres
  #     - KONG_PG_HOST=kong-database
  #     - KONG_CASSANDRA_CONTACT_POINTS=kong-database
  #   command: kong migrations bootstrap
  #   depends_on:
  #     - kong-database
  #   networks: 
  #     - kong-network
  kong:
    image: kong
    container_name: kong
    environment:
      - LC_CTYPE=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
      # - KONG_DATABASE=postgres
      - KONG_DATABASE=off
      # - KONG_PG_HOST=kong-database
      # - KONG_CASSANDRA_CONTACT_POINTS=kong-database
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl    
      - KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml  
    restart: always
    volumes: 
      - ./kong-vol:/usr/local/kong/declarative
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
    # links:
    #   - kong-database:kong-database
    # depends_on:
    #   - kong-migrations
    networks: 
      - kong-network
  konga:
    image: pantsel/konga
    ports:
      - 13370:1337
    links:
      - kong:kong
    container_name: konga
    environment:
      - NODE_ENV=production
    networks: 
      - kong-network
networks: 
  kong-network:
    driver: bridge
#   pgconf:
#     driver: local
#   pglog:
#     driver: local
# docker-compose run kong kong migrations up
