version: '3.4'

services:
  db:
    image: mariadb
    # network_mode: host
    container_name: mariadb-db # 容器名
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci #设置utf8字符集
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3307:3306' #host物理直接映射端口为6606

    environment:
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_DATABASE: yunlai_game
      # MYSQL_USER: sa
      # MYSQL_PASSWORD: sa
    volumes:
      - 'D:/docker/shared/mariadb/:/var/lib/mysql'
    build:
      context: .
      dockerfile: Dockerfile
