version: '3.4'

services:
  redis:
    image: redis:latest
    container_name: my_redis
    restart: always
    ports:
      - "6379:6379"
    # environment:
    #   - ACCEPT_EULA=Y
    #   - SA_PASSWORD=123qwe!@#
    # volumes:
    #   - "D:/docker/shared/mssql:/var/opt/mssql/data"
      # - "D:/filestorage/avatar:/filestorage/avatar"
      # - "D:/aa:/video"
    # build:
    #   context: .
    #   dockerfile: Dockerfile
 